### ISSUE TITLE
Install script for GnuPG

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/enmail#46]
There has been an issue with installing / using various GnuPG versions (#44) -- this is also the case in RNP.

We had a discussion on whether we can extract parts of the RNP build script (which fetches and installs GnuPG) in to a "GnuPG install script" (https://github.com/riboseinc/rnp/issues/611) . Perhaps you could help us create a script that installs GnuPG?

Thanks!

**Comment by ronaldtse** [comment]
This way both EnMail and RNP could use this script.

**Comment by skalee** [comment]
@ronaldtse What do you want to use that install script for? Travis, or other things as well?

Currently, when it comes to Travis, I am leaning towards using Docker. I expect that this will provide easier setup, better performance, and increased stability as compared to custom builds (they randomly fail due to unreliable tarball downloads).

**Comment by ronaldtse** [comment]
@skalee and also used for building the docker containers :wink:

**Comment by skalee** [comment]
@ronaldtse My point is that GPG 2.2 can be obtained with Docker by loading [Ubuntu 16.04 or 18.04 image](https://hub.docker.com/_/ubuntu/). If the GPG install script is needed only to provide a stable CI environment with recent GPG version, then I guess it's easier to use Docker images which are available already.

On the other hand, if you really need to specify particular versions of GPG components, then I guess the install script is necessary…

**Comment by skalee** [comment]
@ronaldtse @ni4 Is it okay to write the build script in Ruby? I can write a Makefile as well, but Ruby makes few things much easier.

**Comment by ronaldtse** [comment]
In my case our containers all have Ruby, but not necessarily the Travis ones... how about in bash? 😉

**Comment by ronaldtse** [comment]
Sure, thank you @skalee!

**Comment by ronaldtse** [comment]
I believe the GnuPG libraries have versions that are specific for GnuPG versions, and we don’t want to select those versions. Instead, can we specify the GnuPG version and just install its latest compatible libraries?

Perhaps @ni4 has a better suggestion.

**Comment by ni4** [comment]
@ronaldtse @skalee I only remember this comment and thread which may be helpful: https://github.com/riboseinc/rnp/issues/611#issuecomment-368871937

**Comment by ronaldtse** [comment]
I totally forgot about it. Great tip @ni4 !

**Comment by skalee** [comment]
Yes, the list pointed in that comment will greatly help in determining the most recent versions of software. However, it won't help in resolving compatible dependencies for older GPG versions. Here I got only one suggestion: let's use popular combinations, e.g. ones used in Ubuntu distros, or ones listed in this popular Gist: https://gist.github.com/mattrude/3883a3801613b048d45b.

Also, after some struggle with the GPG installation process (I've overlooked some tiny but important step), I've ended up with two nearly complete install scripts, one in Ruby, and one in Bash. Finishing them is equally easy to me. IMO the only reason to prefer one rather than another is maintainability. To me, Ruby script is easier to maintain, but I'm not sure about others. Which should I pick then?

cc @ronaldtse @ni4

**Comment by ronaldtse** [comment]
1. I think the popular combinations for other versions (2.0, 2.1 ...) would work as long as they work 😉 

2. If both of them are similar, there are always people who prefer to run bash over Ruby. Let's finish up the Bash one first, and if you have time feel free to do the Ruby one as well.

3. Please push the GPG install script(s) into a new repo, with documentation and a one-line install, thanks!

**Comment by ronaldtse** [comment]
@skalee have we integrated with the new https://github.com/riboseinc/gnu-build-scripts?

**Comment by skalee** [comment]
Yes, I believe it can be marked as done.
